# ACLs básicas (Access Control Lists)
acl localnet src 10.0.0.0/8     # RFC1918 possible internal network
acl localnet src 172.16.0.0/12  # RFC1918 possible internal network
acl localnet src 192.168.0.0/16 # RFC1918 possible internal network
acl localnet src fc00::/7       # RFC 4193 local private network range
acl localnet src fe80::/10      # RFC 4291 link-local (directly plugged) machines

# Puertos seguros permitidos
acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl CONNECT method CONNECT

# Denegar accesos a puertos no seguros
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Permitir acceso desde la red local y localhost
http_access allow localnet
http_access allow localhost

# Denegar el resto por defecto
http_access deny all

# Puerto donde escucha Squid
http_port 3128

# Configuración de la Caché (100 MB en disco, 16 carpetas de nivel 1, 256 de nivel 2)
cache_dir ufs /var/spool/squid 100 16 256
cache_mem 256 MB
maximum_object_size 50 MB
