# ====================================================================
# CONFIGURACIÓN PARA FASE 1: DESPLIEGUE EN CLOUD (AWS EC2)
# ====================================================================
[servidores_cloud]
3.235.48.4 ansible_user=ubuntu ansible_ssh_private_key_file=/ruta/a/tu/llave.pem


# ====================================================================
# CONFIGURACIÓN PARA FASE 2: ENTORNO LOCAL (RED COMUNITARIA)
# ====================================================================
# NOTA DEL PROYECTO: Si deseas realizar el despliegue en tu servidor local,
# debes comentar la IP de AWS de arriba (poniendo un # al inicio de la línea)
# y rellenar los datos de abajo con la IP local de tu máquina.

# [servidores_locales]
# 192.168.1.100 ansible_user=tu_usuario_local ansible_ssh_pass=tu_contraseña
